const one = document.querySelector('.one')
const two = document.querySelector('.two')
const three = document.querySelector('.three')
const four = document.querySelector('.four')
const five = document.querySelector('.five')
const six = document.querySelector('.six')
const seven = document.querySelector('.seven')
const eight = document.querySelector('.eight')
const nine = document.querySelector('.nine')
const zero = document.querySelector('.zero')

const plus = document.querySelector('.plus')
const minus = document.querySelector('.minus')
const multiply = document.querySelector('.multiply')
const divide = document.querySelector('.minus')
const negate = document.querySelector('.negate')
const equal = document.querySelector('.equal')
const result = document.querySelector('.result')
const dot = document.querySelector('.dot')

dot?.addEventListener('click', () => {
  console.log('works')
})